// Common English stopwords plus generic job-posting filler that would
// otherwise pollute keyword extraction and the skill-gap list.
export const STOPWORDS = new Set<string>([
  "a", "about", "above", "after", "again", "against", "all", "am", "an",
  "and", "any", "are", "as", "at", "be", "because", "been", "before",
  "being", "below", "between", "both", "but", "by", "can", "cannot",
  "could", "did", "do", "does", "doing", "down", "during", "each", "few",
  "for", "from", "further", "had", "has", "have", "having", "he", "her",
  "here", "hers", "herself", "him", "himself", "his", "how", "i", "if",
  "in", "into", "is", "it", "its", "itself", "let", "me", "more", "most",
  "must", "my", "myself", "no", "nor", "not", "of", "off", "on", "once",
  "only", "or", "other", "ought", "our", "ours", "ourselves", "out",
  "over", "own", "same", "she", "should", "so", "some", "such", "than",
  "that", "the", "their", "theirs", "them", "themselves", "then", "there",
  "these", "they", "this", "those", "through", "to", "too", "under",
  "until", "up", "very", "was", "we", "were", "what", "when", "where",
  "which", "while", "who", "whom", "why", "will", "with", "would", "you",
  "your", "yours", "yourself", "yourselves", "etc",
  // job-posting filler
  "experience", "years", "year", "strong", "ability", "abilities",
  "skills", "skill", "knowledge", "including", "plus", "preferred",
  "required", "requirement", "requirements", "responsibilities",
  "responsibility", "job", "role", "roles", "position", "positions",
  "candidate", "candidates", "work", "works", "working", "environment",
  "team", "teams", "company", "companies", "opportunity", "opportunities",
  "looking", "join", "using", "use", "used", "help", "helping", "ensure",
  "ensuring", "provide", "providing", "new", "across", "within", "related",
  "similar", "various", "ideal", "ideally", "minimum", "maximum",
  "benefits", "salary", "equal", "employer", "apply", "application",
  "applicants", "please", "who", "we", "you", "our", "us", "an",
  "employment", "employer", "location", "based", "including", "such",
  "e.g", "eg", "i.e", "ie", "etc.", "bonus", "points", "highly", "desired",
  "familiarity", "intern", "build", "driven", "applications",
]);
